### PR TITLE
Nav SideBar + Route Set Up

### PR DESCRIPTION
**Pull request by MinhDucMa97**
**Code changes I made**

- Creating a navigation sidebar component with `react-pro-sidebar` library with functionally navigate to different pages(home, geo chart, bar chart, …)
- Create a `page` folder to include all the pages that will be implemented and used.
- Create a `component` folder to include the necessary component that will be implemented and used.
- Setting up routing with the `react-router-dom` library to navigate to different pages.

**Why I made these changes**

- To easily include navigation sidebar component + functionality to navigate to different pages.
- Setting up basic file structures.

**What feedback I am looking for**

- There currently having some padding/margin that covers the entire existing components. It will be really helpful if any suggestions to help fix that issues.

# Update
**Code changes I made**
- Adjust file name from `BarChart` to `CountryComparison`
- Change `.js` -> .`jsx`

**Why I made these changes**
- Reflect on the feedback from reviewers

**What feedback I am looking for**

- Ready to be merged if nothing needs to adjust further.

### CODE REVIEW

**Review by MrFiszbi1 — CHANGES_REQUESTED** [review]
I am a bit confused with the setup. My understanding is that there would be a homepage that had Geo Chart in it and a comparison page. I would rename BarChart to CountryComparison or something else like that. so we only need two pages. Also, they should be .jsx as we are using react. i think right?

**Comment by MinhDucMa97** [comment]
I was thinking that we should have a home page to briefly describe what we are having for our dashboard. I can totally remove it if you guys thinks it unnecessary.

For renaming the BarChart, do you mean renaming the file, or the actual name on the webpage, or both? 

For changing from `.js` to `.jsx`, do we need to change them manually for each `.js` file, or is there a faster way to do that?

@MrFiszbi1

**Comment by MrFiszbi1** [comment]
Sure you can add a description page. why not. maybe it can have buttons too the two other pages. yeah both, because that page isn't really a barChart. It has a bar chart, but that is not what the page does. Does that make sense? you will need to change each manually. you only need to do that for the three page files.

**Comment by MinhDucMa97** [comment]
Got it. Thanks for the clarification, Jaafar!

**Review by gsampang — APPROVED** [review]
Hey Minh,

I ran your code on my system and everything looks good. 
Like the organization and framework you provided to the app, specifically the page and components folder.
With the caveat that the names of the pages should still be open to change, I think this branch is ready to merge to main.
Great start.

**Review by MrFiszbi1 — APPROVED** [review]

**Pull request merged**
